name: weather-mcp-app
region: nyc
services:
  - name: backend
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      branch: main
      deploy_on_push: true
    http_port: 3001
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # Explicitly specify the run command
    run_command: npm run start
    
    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      # Add your other required environment variables here:
      # - key: ANTHROPIC_API_KEY
      #   scope: RUN_TIME
      #   type: SECRET
      # - key: OPENAI_API_KEY  
      #   scope: RUN_TIME
      #   type: SECRET
      # etc.
    
    # Routes
    routes:
      - path: /
