name: weather-mcp-kd
services:
- name: web
  source_dir: /
  github:
    repo: your-repo/weather-mcp-kd
    branch: stage
  run_command: npm run start:fullstack
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: HOST
    value: "0.0.0.0"
  - key: CORS_ORIGIN
    value: "https://weather-mcp-kd.streamingportfolio.com"
  - key: TTS_TMP_DIR
    value: "/tmp/tts"
  - key: NODE_OPTIONS
    value: "--expose-gc --max-old-space-size=1024"
  build_command: npm run build
  dockerfile_path: Dockerfile