#!/bin/bash

# Digital Ocean Setup Helper Script
echo "🌊 Digital Ocean Deployment Setup Helper"
echo "========================================"
echo ""

echo "📋 Current Repository Status:"
echo "✅ Dockerfile: $(if [ -f "Dockerfile" ]; then echo "Present"; else echo "Missing"; fi)"
echo "✅ .do/app.yaml: $(if [ -f ".do/app.yaml" ]; then echo "Present"; else echo "Missing"; fi)"
echo "✅ Package.json files: $(find . -name "package.json" | wc -l | tr -d ' ') found"
echo ""

echo "🚨 IMPORTANT: Digital Ocean Detection Issue"
echo "Digital Ocean detects BOTH buildpack AND Dockerfile because:"
echo "  - Buildpack: Detected from package.json files"
echo "  - Dockerfile: Detected from Dockerfile"
echo ""

echo "🔧 SOLUTION: Manual Configuration Required"
echo "=========================================="
echo ""
echo "1. Go to Digital Ocean App Platform"
echo "2. Click 'Create App'"
echo "3. Connect your GitHub repository"
echo "4. In the Services section:"
echo "   - Click 'Edit' on the detected service"
echo "   - Change 'Source Type' to 'Dockerfile'"
echo "   - Set Dockerfile path: Dockerfile"
echo "   - Set Source Directory: / (root)"
echo ""

echo "📝 Required Environment Variables:"
echo "=================================="
echo "MASTRA_API_KEY=your_mastra_api_key"
echo "WEATHER_MCP_USER_AGENT=WeatherAgent/1.0 (weather-agent@streamingportfolio.com)"
echo "MUX_TOKEN_ID=your_mux_token_id"
echo "MUX_TOKEN_SECRET=your_mux_token_secret"
echo "ANTHROPIC_API_KEY=your_anthropic_api_key"
echo "DEEPGRAM_API_KEY=your_deepgram_api_key"
echo ""

echo "🎯 Expected Results After Deployment:"
echo "======================================"
echo "Backend Service: https://your-app-name.ondigitalocean.app"
echo "  - Health check: GET /health"
echo "  - Agent endpoint: GET /api/agents/weatherAgent/stream/vnext"
echo ""
echo "Frontend Static Site: https://your-app-name.ondigitalocean.app"
echo "  - React weather chat interface"
echo "  - Connected to backend API"
echo ""

echo "📚 Documentation:"
echo "================="
echo "- See FORCE_DOCKERFILE_DEPLOYMENT.md for detailed steps"
echo "- See DIGITAL_OCEAN_DEPLOYMENT.md for complete guide"
echo ""

echo "✅ Ready for Digital Ocean deployment!"
echo "Remember: You MUST manually select Dockerfile in the Digital Ocean UI"
